# Generated by Django 3.1.5 on 2021-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210116_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
